version: "3.8"
services:
  api:
    build: .
    container_name: api_c
    ports: 
      - '5000:5000'
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    command: sh -c "npm install && npm run dev"